### ISSUE TITLE
Crime Data Not Showing Correctly

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#129]
It seems that the crime data points on the map don't seem to match up with the numbers in the drop down report. For example, in the financial district, the drop down report says there are 44 homicides in the previous year but the map data shows 7 homicides and only a portion of those were last year.

**Comment by AmandaWilsonKC** [comment]
Another place for pulling crime data would be the County's GIS. Need to compare data from the County's GIS and the City's open data but i wonder if our app could easily help compare the two??

http://arcgisweb.jacksongov.org/arcgis/rest/services/COMBAT/ViolentCrimePoints/MapServer  Part I Violent Crime (County-wide, dates depend on agency – KCPD data through last week)

http://maps.jacksongov.org/combat/  COMBAT’s web mapping application – it has the Part I Violent Crime data

**Comment by moldybeats** [comment]
Seems like these Jackson County COMBAT URLs have moved:

https://jcgis.jacksongov.org/combat/combat.htm

https://jcgis.jacksongov.org/arcgis/rest/services/COMBAT/ViolentCrimePoints/MapServer/0

**Comment by buzwells** [comment]
Since I am already working on the crime tab, I can take a look at this issue. After I close out the https://github.com/codeforkansascity/Neighborhood-Dashboard/issues/142, I will do a deeper dive into the data to try to reconcile our own views internally. Then I will try to compare our data to data from other sites.

**Comment by buzwells** [comment]
Looking more closely at the data, it appears that we are counting each record in the dataset as a crime. But it looks as though there can be multiple rows for a single crime, all linked together by a "report no" field. Each separate row appears to relate to a different person involved in the crime (e.g., suspects, arrestees and victims, identified by the "involvement" field). If this is correct - and I certainly need to do a little more digging on this - then we probably only want to count once for the whole incident.

**Comment by buzwells** [comment]
I pushed and merged some improvements to the display of crime data:
* The crime report now counts each incident only once. Previously, we were over-reporting incidents by counting each involved person as a separate crime.
* Merge incidents at the same intersection into a single marker.
* Display an incident count for each marked location.
I think this is an improvement, but there is still more fine-tuning to do. For instance:
* For some neighborhoods, counts by marker are off by one or two from the counts in the crime report (when using last year in the Filters). I believe this is because the report is driven by a query that assumes everything in the database for a particular year relates to that year (no date conditions specified). Adding a date condition should fix the problem, but will test to see.
* Our legends assume each location has only a single crime category. Because locations can now have multiple crimes, they can also have multiple categories of crime. Will need a design to handle that.

**Comment by buzwells** [comment]
Another additional issue: some filter checkboxes are not sending down the right codes (they appear broken), which results in no pins being dropped even when the violations exist.

**Comment by buzwells** [comment]
There were 4 crime filters that were not working properly because they were not associated with any codes behind the scenes: Sex Offenses (both), Counterfeiting and Domestic Nonviolent. I've made the necessary fixes, including changing the label of "Counterfeiting" to "Forgery/Counterfeiting" to reflect the underlying NIBRS documentation. I will be pushing and deploying the changes shortly.

**Comment by buzwells** [comment]
Fix has been deployed. Closing this large issue. Will open smaller issues for minor remaining improvements.
