### ISSUE TITLE
Update + Rename Problem Tenants Query

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#139]
Change name of query on Misc. tab from Problem Tenants to Problem Landlords. This should pull up rental properties (where the physical address does not match the owner address) and there are code violations. Will need to double check that the KCMO open data code violations are being pulled from the correct dataset...

**Comment by moldybeats** [comment]
A couple notes as I dived into this issue:

1. To find rental properties, we compare the `county_owner_address` to the `street_address` obtained from the Address API. That sounds right, but I'm not sure where this info comes from and if it's current. Quite a few addresses were missing the `county_owner_address`. 

2. The request to the KCMO Property Violations API uses a old endpoint URL, but even after trying the new-style endpoint with the same neighborhood coordinate data, I wasn't able to get any violations for any neighborhoods I tested, even when including closed violations. I wonder if something has changed with Socrata's `within_polygon` method?

**Comment by buzwells** [comment]
It looks like `within_polygon` works for some KCMO datasets (e.g., crime and 311), but not for property violations. We noticed that the property violations dataset includes the latitude and longitude fields in its schema, but they do not appear to be populated. Datasets where `within_polygon` works properly appear to have those fields populated. The documentation suggests that these fields drive the determination of whether the location point is within the described polygon. Notably, property violations does include a neighborhood name field. When this is used in place of the polygon keyword/function, the query returns the matching violations in the neighborhood. One possibility is to leverage this field for property violations. But before doing that we can check with Eric Roche to understand better whether these fields used to be populated (and whether there is any other reason the queries used to work but no longer do).

**Comment by moldybeats** [comment]
In addition to the issues with the KCMO data sets mentioned above, it seems there are a few issues with the Address API we'll need to work through in order to accurately identify rentals by comparing `street_address` to `county_owner_address`. The Neighborhood Dashboard uses the `address-by-neighborhood` endpoint for this.

- The Address API doesn't return any results for some neighborhoods.
- Some results are missing all data, including the `street_address`. These seem to be completely empty records, so I'm not sure why they're returned at all.
- Other records have a `street_address` and other info (including the `county_id` APN), but no `county_owner_address`. When I checked the Parcel Viewer, an owner was listed, so it seems like an issue with the Address API rather than missing information about the property itself.

[address_by_neighborhoods_stats-20190204.xlsx](https://github.com/codeforkansascity/Neighborhood-Dashboard/files/2829146/address_by_neighborhoods_stats-20190204.xlsx)

**Comment by moldybeats** [comment]
I updated the filter label for this as part of issue #132, but there's still some stuff behind the scenes that uses the "problem renter" terminology (eg. the ProblemRenters class, the problem-renters query parameter, etc.). It would be nice to update all those for consistency.

**Comment by moldybeats** [comment]
I got rid of the "problem renters" terminology behind the scenes, so I think this issue is complete.
